<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_psw</name>
   <tag></tag>
   <elementGuidId>80f83833-a680-4133-bfb6-67c7bf617162</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;psw&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='psw']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fd47b659-90d1-425a-8488-a3f78a7cddf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>e8e00b9a-97e2-4b77-a5b2-d221b50bfa94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Password</value>
      <webElementGuid>3f57762f-9be7-4728-8d21-d5ace1e20efe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>psw</value>
      <webElementGuid>d4b30a5a-bfd5-4de3-9e2c-f09a024ad900</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;HTML1&quot;)/div[@class=&quot;widget-content&quot;]/form[1]/div[@class=&quot;container&quot;]/input[2]</value>
      <webElementGuid>5dadd828-e59e-4d0d-9e0c-221924f405ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='psw']</value>
      <webElementGuid>e4bfcb99-a6c2-476d-b53a-6e1d9fc73514</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='HTML1']/div/form/div/input[2]</value>
      <webElementGuid>21a08ccb-1df1-4714-9049-41143e5626e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>7ea6a0b4-b231-4d5f-b790-2a407f2e8cf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @placeholder = 'Enter Password' and @name = 'psw']</value>
      <webElementGuid>c33ccad4-4b76-4623-9694-b4787b31615b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
