<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>DataDrivenDemo</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>1acc9c98-02fc-45bc-b182-5c5b93bca32c</testSuiteGuid>
   <testCaseLink>
      <guid>f614af86-9a05-4b96-aa5b-94b0d092a9db</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Demo/DataDrivenTestingDemo</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>a06f7933-9884-4704-8525-65b3e2e58784</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Data1</testDataId>
      </testDataLink>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>b053cf72-3612-473e-9ba2-b5b2d829ba2e</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/LoginData</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>b053cf72-3612-473e-9ba2-b5b2d829ba2e</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>1614fe02-0cf1-40fd-bf60-57b393b73f7c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>b053cf72-3612-473e-9ba2-b5b2d829ba2e</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>ff14a902-a826-402d-8f32-9bce60808cc5</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
