<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Keys</name>
   <tag></tag>
   <elementGuidId>610862af-da69-44ba-8bd2-8603501afbf3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='class-summary.tabpanel']/div/div[77]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col-first.odd-row-color.class-summary.class-summary-tab3 > a[title=&quot;enum class in org.openqa.selenium&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1aaa42bf-f1a9-4eeb-8cd7-ed0ba3c83ec0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>Keys.html</value>
      <webElementGuid>bc5ccc45-fffd-41f5-ae6f-4278090b62c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>enum class in org.openqa.selenium</value>
      <webElementGuid>62607bbf-61e1-4d74-a199-50e607b321ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Keys</value>
      <webElementGuid>7907d651-0a1f-4d88-a93e-2062e5d8729a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;class-summary.tabpanel&quot;)/div[@class=&quot;summary-table two-column-summary&quot;]/div[@class=&quot;col-first odd-row-color class-summary class-summary-tab3&quot;]/a[1]</value>
      <webElementGuid>d40f46fa-5a25-441b-b38f-9092ae323543</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='class-summary.tabpanel']/div/div[77]/a</value>
      <webElementGuid>86a5bf6e-9198-442d-92be-6757323cd932</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Keys')])[2]</value>
      <webElementGuid>30c0abde-c88c-405b-8a63-b36d46a86e32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Indicates that a driver can execute JavaScript, providing access to the mechanism to do so.'])[1]/following::a[1]</value>
      <webElementGuid>bbde960e-2ef5-4868-86de-c287e9e31054</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JavascriptExecutor'])[1]/following::a[1]</value>
      <webElementGuid>7810016b-3684-4bf5-906a-61629544858f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Representations of pressable keys that aren', &quot;'&quot;, 't text.')])[1]/preceding::a[1]</value>
      <webElementGuid>6b37fc47-f9e2-42bf-9059-deeff0fbac3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MutableCapabilities'])[1]/preceding::a[1]</value>
      <webElementGuid>6def1eae-ed45-404a-b733-e781ee58e01e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Keys']/parent::*</value>
      <webElementGuid>69dd06c2-4fb2-4479-8dbb-00f47f38f62f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'Keys.html')])[2]</value>
      <webElementGuid>ecde4a9e-5dce-4c6b-83b0-b7e47fae45d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[77]/a</value>
      <webElementGuid>851983e5-d74d-4f6a-93a9-fcd21fc48bca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'Keys.html' and @title = 'enum class in org.openqa.selenium' and (text() = 'Keys' or . = 'Keys')]</value>
      <webElementGuid>24a89d60-8908-42c5-ad53-dfdf6c500862</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
