<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Classes</name>
   <tag></tag>
   <elementGuidId>80df8017-fbc9-4675-abc4-96e9df06694d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='class-summary-tab2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#class-summary-tab2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9918c488-a56f-4839-909a-4b6f0302d3e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>class-summary-tab2</value>
      <webElementGuid>3953ceed-4337-4090-bbbe-8990efe27586</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>08e46e26-d854-4fc3-9585-492a92975586</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>028c7915-29cf-4003-9e5e-f407f376504d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>class-summary.tabpanel</value>
      <webElementGuid>8bcc1422-1199-4233-b5b8-99a4c4602357</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>1f7063b5-c89e-4848-8e30-62aada7d0964</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>switchTab(event)</value>
      <webElementGuid>dbf5c490-9a94-4327-9766-c3f22e3133dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>show('class-summary', 'class-summary-tab2', 2)</value>
      <webElementGuid>9384ebf4-4679-40e6-a7cb-d43d5e058ed6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>table-tab</value>
      <webElementGuid>00e385c7-843f-4c80-a533-92d7980f19b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Classes</value>
      <webElementGuid>fc09fe04-6c46-42eb-a625-c54ae72835f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;class-summary-tab2&quot;)</value>
      <webElementGuid>2a5a6483-dac2-4798-90a5-9e9d0f1f98ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='class-summary-tab2']</value>
      <webElementGuid>b5dc06d1-fd06-4457-8182-16a3fbf8374f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='class-summary']/div/button[3]</value>
      <webElementGuid>766b86a3-740c-452f-89a1-9ca64b30ad19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Interfaces'])[1]/following::button[1]</value>
      <webElementGuid>2817df53-326a-4281-a169-03f6a2880ae3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Classes and Interfaces'])[1]/following::button[2]</value>
      <webElementGuid>edb117a1-996f-4efa-9fd6-735f9bf14bba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enum Classes'])[1]/preceding::button[1]</value>
      <webElementGuid>9c8bcf20-38e0-461a-a431-35560c08f6be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Exceptions'])[1]/preceding::button[2]</value>
      <webElementGuid>b6f0ccb4-20e9-4fd3-9e5f-87f6ecd5fc0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Classes']/parent::*</value>
      <webElementGuid>097ad6d0-a192-4fd1-b2fc-2733b4900a5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[3]</value>
      <webElementGuid>da9ca138-5b35-4ca3-afa5-29d95cef3ded</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'class-summary-tab2' and (text() = 'Classes' or . = 'Classes')]</value>
      <webElementGuid>03882fbd-4305-4400-b488-a35e997b1fae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
