<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Run</name>
   <tag></tag>
   <elementGuidId>665afb17-e8a4-4dad-a86f-a12e5c30ca41</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='runbtn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#runbtn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8beeebd7-0701-4100-a736-af14f93ca95e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>runbtn</value>
      <webElementGuid>bee81d33-b10c-4975-9bb4-053ed7e29214</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w3-button w3-bar-item w3-hover-white w3-hover-text-green ga-tryit</value>
      <webElementGuid>7df9e66b-4fde-474e-a79a-fcccb07b2ddc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>submitTryit(1);uic_r_p();</value>
      <webElementGuid>15a882cc-bf27-4234-b9a4-66a7c12a4a76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Run ❯</value>
      <webElementGuid>7798e9eb-f74c-415d-b14c-5964987755bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;runbtn&quot;)</value>
      <webElementGuid>4f461e80-6d5f-4d81-a039-f39378799cf7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='runbtn']</value>
      <webElementGuid>20259c13-07c8-47ad-9e65-666a7d245867</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='own'])[1]/preceding::button[1]</value>
      <webElementGuid>c6ef1dca-4526-4dae-bc16-6638f6f94a8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Run ❯']/parent::*</value>
      <webElementGuid>aa31dea0-08c5-4c45-9ea2-e3a8522b42e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>fd1cd590-9b3c-4556-8f87-895adca31ae1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'runbtn' and (text() = 'Run ❯' or . = 'Run ❯')]</value>
      <webElementGuid>874da5e1-d047-4014-96a6-02e9847dad19</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
