<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_alert_toolbar__button toolbar__button_run</name>
   <tag></tag>
   <elementGuidId>5ab1e1f2-f077-4b84-a71d-6344f85fcb6b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='0jih46u7h4']/div/div/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.toolbar__button.toolbar__button_run</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8e36adcd-b60c-4785-a1c5-558c3973beb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>c149ebef-ed59-40c6-8bf0-5a3b04fcdeec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>run</value>
      <webElementGuid>ad7cf499-e87d-414d-be69-a99f399a8f66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action</name>
      <type>Main</type>
      <value>run</value>
      <webElementGuid>abe2cf8d-a878-4267-aa36-08d331979afe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>toolbar__button toolbar__button_run</value>
      <webElementGuid>405111e3-7af3-4a57-89c6-696be7f83e0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;0jih46u7h4&quot;)/div[@class=&quot;codebox code-example__codebox&quot;]/div[@class=&quot;toolbar codebox__toolbar&quot;]/div[@class=&quot;toolbar__tool&quot;]/a[@class=&quot;toolbar__button toolbar__button_run&quot;]</value>
      <webElementGuid>a456d9d7-3884-4243-9e04-08d9e7c4cba9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='0jih46u7h4']/div/div/div/a</value>
      <webElementGuid>f83db9cf-bc92-4e06-8f17-fa55d3180236</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[2]</value>
      <webElementGuid>96ed3a59-fbc9-47e2-b930-e217d805a2aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//article/div[2]/div/div/div/div/a</value>
      <webElementGuid>a5332b40-0df1-4309-8dd3-82be40bfdd8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @title = 'run']</value>
      <webElementGuid>358f62f1-89fc-4162-b7cf-da62abfcf026</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gjz4r0dwu7']/div/div/div/a</value>
      <webElementGuid>77e18e3b-fb01-4186-9e8b-1e4b9ae191a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
