<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_java.lang.Object</name>
   <tag></tag>
   <elementGuidId>183eb35f-cb34-4aef-9578-ed50faf373d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'java.lang.Object')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.external-link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e15ff9f9-552f-4762-9a5c-b1f8c759092a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/lang/Object.html</value>
      <webElementGuid>b6cce547-cb2d-4dc2-aee9-d578c3f2ecfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>class or interface in java.lang</value>
      <webElementGuid>e0b899a1-7427-403b-9947-0ce7c365cfc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>external-link</value>
      <webElementGuid>be8eac65-f063-419e-9059-b1e78ea37200</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>java.lang.Object</value>
      <webElementGuid>74a1238c-ff5d-4499-b1b8-392d58e0af68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;class-declaration-page&quot;]/div[@class=&quot;flex-box&quot;]/div[@class=&quot;flex-content&quot;]/main[1]/div[@class=&quot;inheritance&quot;]/a[@class=&quot;external-link&quot;]</value>
      <webElementGuid>9b93bad9-b47b-4044-89e4-151fad6e0dac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'java.lang.Object')]</value>
      <webElementGuid>a50066be-2239-4582-b122-8776389c13c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enum Class Keys'])[1]/following::a[1]</value>
      <webElementGuid>fa555e81-e9d4-4fbd-9cd6-9414e21df6c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='org.openqa.selenium'])[1]/following::a[1]</value>
      <webElementGuid>1e35655d-811d-4231-ab8e-aa843ccd09be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='java.lang.Enum'])[1]/preceding::a[1]</value>
      <webElementGuid>3482cc40-56d6-4871-bdd4-2cb50808e283</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='java.lang.Object']/parent::*</value>
      <webElementGuid>52cec5ac-422d-4ac7-975b-89d9322c0863</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/lang/Object.html')]</value>
      <webElementGuid>3c980b2c-0fae-4f4f-a34c-417aea1ee4f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>0119dbc5-a254-49ce-acc0-353fa6cbbc07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/lang/Object.html' and @title = 'class or interface in java.lang' and (text() = 'java.lang.Object' or . = 'java.lang.Object')]</value>
      <webElementGuid>e869df23-6cd0-4846-ae65-9752a93c9bec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
